routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProjectsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('projects', ProjectsController::class);

app/Models/Projects.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Projects extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Projects;
use GuzzleHttp\Handler\Proxy;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;
use SebastianBergmann\CodeCoverage\Report\Xml\Project;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Projects::get();
        return View::make('projects.index', ['projects' => $projects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $projects = new Projects;
        $projects->title = $request->input('title');
        $projects->description = $request->input('description');
        $projects->date = $request->input('date');
        $projects->save();    
        return redirect()->route('projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $title = Projects::where('id', $id)->first();
        return View::make('projects.show', ['project' => $title]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $title = Projects::where('id', $id)->first();
        return View::make('projects.edit', ['project' => $title]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $title = Projects::find($id);
        $title->title = $request->input('title');
        $title->description = $request->input('description');
        $title->date = $request->input('date');
        $title->save();
        return redirect()->route('projects.show', ['project' => $title]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $projects = Projects::where('id', $id)->delete();
        return redirect()->route('projects.index');
    }
}

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <main>@yield('content')</main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

resources/views/projects/create.blade.php
@extends('layout.app')

@section('title', 'create')

@section('content')

    <form action="{{ route('projects.store') }}" method="post">
        @csrf    
        <input type="text" name="title" value="">
        <input type="text" name="description" value="">
        <input type="date" name="date" value="">
        <input type="submit" value="Create">
    </form>

@endsection

resources/views/projects/edit.blade.php
@extends('layout.app')

@section('title', 'update')

@section('content')
    <form action="{{ route('projects.update', ['project' => $project->id]) }}" method="post">
        @csrf
        <input type="text" name="title" value="{{ $project->title }}">
        <input type="text" name="description" value="{{ $project->description }}">
        <input type="date" name="date" value="{{ $project->date }}">
        @method('PUT')
        <input type="submit" value="Update">
    </form>

@endsection

resources/views/projects/index.blade.php
@extends('layout.app')

@section('title', 'random')

@section('content')
    <ul>
        @forelse($projects as $project)

            <li>
                {{ $project->title }}

                <form action="{{ route('projects.destroy', ['project' => $project->id]) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <input type="submit" value="delete">
                </form>
            </li>

        @empty
            <p>No projects</p>
        @endforelse
    </ul>
@endsection

resources/views/projects/show.blade.php
@extends('layout.app')

@section('title', 'show')

@section('content')
    @if( $project )
        {{ $project->title }}
        {{ $project->description }}
        {{ $project->date }}
    @else
        "Fuck you"
    @endif

@endsection